[build]
  base = "client"
  publish = "client/build"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18" # or whatever Node version you’re using

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
